// Mocks generated by Mockito 5.3.2 from annotations
// in doomi/test/app_initialization_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:doomi/interfaces/auth.dart' as _i3;
import 'package:doomi/interfaces/local_storage.dart' as _i6;
import 'package:doomi/interfaces/online_storage.dart' as _i4;
import 'package:doomi/interfaces/themes.dart' as _i8;
import 'package:doomi/models/user.dart' as _i2;
import 'package:doomi/utils/enums.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUser_0 extends _i1.SmartFake implements _i2.User {
  _FakeUser_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IAuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAuthService extends _i1.Mock implements _i3.IAuthService {}

/// A class which mocks [IOnlineStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockIOnlineStorage extends _i1.Mock implements _i4.IOnlineStorage {
  @override
  _i5.Future<_i2.User?> getUser(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getUser,
          [id],
        ),
        returnValue: _i5.Future<_i2.User?>.value(),
        returnValueForMissingStub: _i5.Future<_i2.User?>.value(),
      ) as _i5.Future<_i2.User?>);
  @override
  _i5.Future<_i2.User> saveUser(_i2.User? user) => (super.noSuchMethod(
        Invocation.method(
          #saveUser,
          [user],
        ),
        returnValue: _i5.Future<_i2.User>.value(_FakeUser_0(
          this,
          Invocation.method(
            #saveUser,
            [user],
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i2.User>.value(_FakeUser_0(
          this,
          Invocation.method(
            #saveUser,
            [user],
          ),
        )),
      ) as _i5.Future<_i2.User>);
}

/// A class which mocks [ILocalStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockILocalStorage extends _i1.Mock implements _i6.ILocalStorage {
  @override
  _i5.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  void saveLocale(_i7.DoomiLocale? locale) => super.noSuchMethod(
        Invocation.method(
          #saveLocale,
          [locale],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void saveTheme(_i8.ITheme? theme) => super.noSuchMethod(
        Invocation.method(
          #saveTheme,
          [theme],
        ),
        returnValueForMissingStub: null,
      );
}
